COD_MW_MODES = {
    "conf": "Kill Confirmed",
    "conf_hc": "Kill Confirmed Hardcore",
    "cyber": "Cyber Attack",
    "cyber_hc": "Cyber Attack Hardcore",
    "dd": "Deathmatch Domination",
    "dd_hc": "Deathmatch Domination Hardcore",
    "dom": "Domination",
    "dom_hc": "Domination Hardcore",
    "dm": "Free For All",
    "hq": "Headquarters",
    "hq_hc": "Headquarters Hardcore",
    "infect": "Infected",
    "koth": "Hardpoint",
    "sd": "Search & Destroy",
    "sd_hc": "Search & Destroy Hardcore",
    "siege": "{gameMode}",
    "tdef": "Team Defender",
    "war": "Team Deathmatch",
    "war_hc": "Team Deathmatch Hardcore",
    "arm": "Ground War",
    "arena": "{gameMode}",
    "grnd": "Grind",
    "br_brquads": "Quads",
    "br_brtrios": "Trios",
    "br_brduos": "Duos",
    "br_brsolo": "Solo",
    "br_89": "Quads Solo",
    "br_mini_miniroyale": "Mini Royale"
}

COD_MW_MAPS = {
    "mp_cave_am": "Azhir Cave",
    "mp_farms2_gw": "{mapName}",
    "mp_spear": "Rammaza",
    "mp_m_stadium": "{mapName}",
    "mp_m_showers": "{mapName}",
    "mp_promenade_gw": "{mapName}",
    "mp_riverside_gw": "{mapName}",
    "mp_runner": "{mapName}",
    "mp_spear_pm": "{mapName}",
    "mp_vacant": "{mapName}",
    "mp_hackney_am": "{mapName}",
    "mp_rust": "Rust",
    "mp_shipment": "{mapName}",
    "mp_m_cornfield": "{mapName}",
    "mp_hackney_yard": "{mapName}",
    "mp_m_pine": "{mapName}",
    "mp_m_train": "{mapName}",
    "mp_hideout": "{mapName}",
    "mp_m_wallco2": "{mapName}",
    "mp_layover_gw": "{mapName}",
    "mp_quarry2": "{mapName}",
    "mp_m_overwinter": "{mapName}",
    "mp_cave": "{mapName}",
    "mp_village2": "{mapName}",
    "mp_m_speed": "Shoot House",
    "mp_boneyard_gw": "{mapName}",
    "mp_malyshev": "{mapName}",
    "mp_petrograd": "{mapName}",
    "mp_raid": "{mapName}",
    "mp_harbor": "Suldal Harbor",
    "mp_broadcast2": "{mapName}",
    "mp_m_speedball": "{mapName}",
    "mp_garden": "Cheshire Park",
    "mp_m_king": "{mapName}",
    "mp_aniyah_tac": "{mapName}",
    "mp_m_cargo": "{mapName}",
    "mp_euphrates": "Euphrates Bridge",
    "mp_downtown_gw": "{mapName}",
    "mp_backlot2": "{mapName}",
    "mp_scrapyard": "Zhokov Scrapyard",
    "mp_deadzone": "{mapName}",
    "mp_m_overunder": "{mapName}",
    "mp_oilrig": "Petrov Oil Rig",
    "mp_piccadilly": "{mapName}",
    "mp_m_trench": "{mapName}",
    "mp_emporium": "{mapName}",
    "mp_m_stack": "{mapName}",
    "mp_m_cage": "{mapName}",
    "mp_runner_pm": "{mapName}",
    "mp_m_hill": "{mapName}",
    "mp_m_fork": "{mapName}",
    "mp_port2_gw": "{mapName}",
    "mp_aniyah": "{mapName}",
    "mp_crash2": "Crash",
    "mp_hardhat": "{mapName}",
    "mp_don3": "Verdansk",
    "mp_donetsk": "Verdansk"
}